[ERROR]2023.05.02 16:41:09 : python执行的错误信息HTTPConnectionPool(host='192.168.3.22', port=9004): Max retries exceeded with url: /api/eod/all-business-date (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000236FA5B1C30>, 'Connection to 192.168.3.22 timed out. (connect timeout=None)'))
[ERROR]2023.05.02 16:41:30 : python执行的错误信息HTTPConnectionPool(host='192.168.3.22', port=9004): Max retries exceeded with url: /api/trade/entry/query/option/trade?tradeEntryId=0011430 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000236FA5B21D0>, 'Connection to 192.168.3.22 timed out. (connect timeout=None)'))
[ERROR]2023.05.02 16:42:12 : python执行的错误信息HTTPConnectionPool(host='192.168.3.22', port=9004): Max retries exceeded with url: /api/eod/all-business-date (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C1C39ADC00>, 'Connection to 192.168.3.22 timed out. (connect timeout=None)'))
[ERROR]2023.05.02 16:42:33 : python执行的错误信息HTTPConnectionPool(host='192.168.3.22', port=9004): Max retries exceeded with url: /api/trade/entry/query/option/trade?tradeEntryId=0011654 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001C1C39AE200>, 'Connection to 192.168.3.22 timed out. (connect timeout=None)'))
